### ISSUE TITLE
Multiple options under the same key?

### ISSUE THREAD

**Issue by xjzh123** [Double-oxygeN/gulp-nim#12]
Sorry, I actually don't use gulp or this plugin. But I wonder, it seems that this plugin doesn't support `-d:release -d:ssl` etc. If you have time, could you add it so that this plugin can be more complete?

**Comment by Double-oxygeN** [comment]
Thank you for opening an issue!

I think the syntax below would be good (currently not supported):

```js
nim({ d: ['release', 'ssl'] })
```
